# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/FPGA/secure_zynq/.Xil/Vivado-44380-DESKTOP-71JN9RA/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/ec67/hdl {
      D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/ec67/hdl {
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_processing_system7_0_0/synth/base_zynq_processing_system7_0_0.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/synth/base_zynq_xbar_0.v
      E:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/synth/base_zynq.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_2/synth/base_zynq_auto_pc_2.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_0/synth/base_zynq_auto_pc_0.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_1/synth/base_zynq_auto_pc_1.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/823f/hdl/verilog/example_BUS_A_s_axi.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/823f/hdl/verilog/example.v
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_example_0_2/synth/base_zynq_example_0_2.v
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_22 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/f71e/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/synth/base_zynq_axi_gpio_0_0.vhd
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/synth/base_zynq_blk_mem_gen_0_0.vhd
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_0/synth/base_zynq_axi_bram_ctrl_0_0.vhd
      e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/synth/base_zynq_rst_ps7_0_50M_0.vhd
      E:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/hdl/base_zynq_wrapper.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_bram_ctrl_v4_1_2 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/a002/hdl/axi_bram_ctrl_v4_1_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_5 e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ipshared/276e/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top base_zynq_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/FPGA/secure_zynq/.Xil/Vivado-44380-DESKTOP-71JN9RA/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
