# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/first.xdc

# Block Designs: bd/micro_mcu/micro_mcu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu || ORIG_REF_NAME==micro_mcu} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_processing_system7_0_0/micro_mcu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_processing_system7_0_0 || ORIG_REF_NAME==micro_mcu_processing_system7_0_0} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_axi_gpio_0_0/micro_mcu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_axi_gpio_0_0 || ORIG_REF_NAME==micro_mcu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_ps7_0_axi_periph_0/micro_mcu_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_ps7_0_axi_periph_0 || ORIG_REF_NAME==micro_mcu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_rst_ps7_0_50M_0/micro_mcu_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_rst_ps7_0_50M_0 || ORIG_REF_NAME==micro_mcu_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_xbar_0/micro_mcu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_xbar_0 || ORIG_REF_NAME==micro_mcu_xbar_0} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_axi_bram_ctrl_0_1/micro_mcu_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_axi_bram_ctrl_0_1 || ORIG_REF_NAME==micro_mcu_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_axi_bram_ctrl_0_bram_1/micro_mcu_axi_bram_ctrl_0_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==micro_mcu_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_auto_pc_1/micro_mcu_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_auto_pc_1 || ORIG_REF_NAME==micro_mcu_auto_pc_1} -quiet] -quiet

# IP: bd/micro_mcu/ip/micro_mcu_auto_pc_0/micro_mcu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==micro_mcu_auto_pc_0 || ORIG_REF_NAME==micro_mcu_auto_pc_0} -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_processing_system7_0_0/micro_mcu_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_mcu_processing_system7_0_0 || ORIG_REF_NAME==micro_mcu_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_axi_gpio_0_0/micro_mcu_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_mcu_axi_gpio_0_0 || ORIG_REF_NAME==micro_mcu_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_axi_gpio_0_0/micro_mcu_axi_gpio_0_0_ooc.xdc

# XDC: bd/micro_mcu/ip/micro_mcu_axi_gpio_0_0/micro_mcu_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_mcu_axi_gpio_0_0 || ORIG_REF_NAME==micro_mcu_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_rst_ps7_0_50M_0/micro_mcu_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_mcu_rst_ps7_0_50M_0 || ORIG_REF_NAME==micro_mcu_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_rst_ps7_0_50M_0/micro_mcu_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==micro_mcu_rst_ps7_0_50M_0 || ORIG_REF_NAME==micro_mcu_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/micro_mcu/ip/micro_mcu_axi_bram_ctrl_0_bram_1/micro_mcu_axi_bram_ctrl_0_bram_1_ooc.xdc

# XDC: bd/micro_mcu/ip/micro_mcu_auto_pc_1/micro_mcu_auto_pc_1_ooc.xdc

# XDC: bd/micro_mcu/ip/micro_mcu_auto_pc_0/micro_mcu_auto_pc_0_ooc.xdc

# XDC: bd/micro_mcu/micro_mcu_ooc.xdc
