# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache E:/FPGA/secure_zynq/.Xil/Vivado-44380-DESKTOP-71JN9RA/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/secure_zynq/secure_zynq.cache/wt [current_project]
set_property parent.project_path E:/FPGA/secure_zynq/secure_zynq.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/FPGA/secure_zynq/axi_lite_hls/proj_axi_lite [current_project]
update_ip_catalog
set_property ip_output_repo e:/FPGA/secure_zynq/secure_zynq.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/hdl/base_zynq_wrapper.vhd
add_files E:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/base_zynq.bd
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_2/base_zynq_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_example_0_2/constraints/example_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA/secure_zynq/secure_zynq.srcs/sources_1/bd/base_zynq/base_zynq_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/secure_zynq/secure_zynq.srcs/constrs_1/new/secure.xdc
set_property used_in_implementation false [get_files E:/FPGA/secure_zynq/secure_zynq.srcs/constrs_1/new/secure.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top base_zynq_wrapper -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef base_zynq_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file base_zynq_wrapper_utilization_synth.rpt -pb base_zynq_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
